 CREATE TABLE IF NOT EXISTS `ea_test_table1` (
  `id` bigint(20) NOT NULL auto_increment,
  `valint` int(11) NOT NULL,
  `valdate` date NOT NULL,
  `valenum` enum('one','two','three') NOT NULL,
  `valtinyint` tinyint(4) NOT NULL,
  `valsmallint` smallint(6) NOT NULL,
  `valvarchar` varchar(32) NOT NULL,
  `valmediumint` mediumint(9) NOT NULL,
  `valfloat` float NOT NULL default '0',
  `valdouble` double NOT NULL,
  `valdecimal` decimal(10,0) NOT NULL,
  `valdatetime` datetime NOT NULL,
  `valtimestamp` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `valtime` time NOT NULL,
  `valyear` year(4) NOT NULL,
  `valchar` char(32) NOT NULL,
  `valtinyblob` tinyblob NOT NULL,
  `valtinytext` tinytext NOT NULL,
  `valblob` blob NOT NULL,
  `vamediumblob` mediumblob NOT NULL,
  `valmediumtext` mediumtext NOT NULL,
  `vallongblob` longblob NOT NULL,
  `vallongtext` longtext NOT NULL,
  `valbool` tinyint(1) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;